# Generated by Django 5.1.1 on 2024-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_customer_rename_sold_item_sold_at_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="checked_out",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="sold_at",
            field=models.DateTimeField(),
        ),
    ]
