# Generated by Django 5.1.1 on 2024-09-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_item_sold_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="price_in_cents",
            field=models.PositiveIntegerField(),
        ),
    ]
