# Generated by Django 5.1.1 on 2024-09-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_alter_customer_email_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="checked_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
