# Generated by Django 5.1.1 on 2024-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("total_in_cents", models.PositiveIntegerField(default=0)),
                ("items", models.ManyToManyField(to="shop.item")),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
