# Generated by Django 5.1.1 on 2024-09-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_cart_customer_remove_cart_items_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checked_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
