# Generated by Django 5.1.1 on 2024-09-12 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_order_checked_out"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
    ]
