# Generated by Django 4.2.16 on 2024-09-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0005_order_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="checked_out",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_in_cents",
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_in_cents", models.PositiveIntegerField(default=0)),
                ("items", models.ManyToManyField(to="shop.item")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.cart",
            ),
            preserve_default=False,
        ),
    ]
