# Generated by Django 4.2.16 on 2024-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_cart_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
